version: '3.9'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: scripts/docker/dev/Dockerfile
    volumes:
      - ./backend:/sms-gateway/backend
    ports:
      - "9000:9000"
    depends_on:
      - db
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  db:
    container_name: pg_db
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
#  pgAdmin:
#    container_name: pg_admin
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: postgres@postgres.postgres
#      PGADMIN_DEFAULT_PASSWORD: postgres
#    ports:
#      - "5433:80"

volumes:
  postgres_data: