# Generated by Django 4.1.4 on 2022-12-24 20:51

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=600, verbose_name="Содержимое")),
                (
                    "phone_number",
                    models.CharField(
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Телефон должен быть введен в формете: '+999999999'. От 9 до 15 цифр.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "send_to",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            max_length=17,
                            validators=[
                                django.core.validators.RegexValidator(
                                    message="Телефон должен быть введен в формете: '+999999999'. От 9 до 15 цифр.",
                                    regex="^\\+?1?\\d{9,15}$",
                                )
                            ],
                        ),
                        size=None,
                    ),
                ),
                (
                    "is_sent",
                    models.BooleanField(
                        default=False, verbose_name="Сообщение перешло в отправку"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "db_table": "messages",
                "managed": True,
            },
        ),
    ]
